
import { SampleText, SentimentLabel } from './types';

export const SAMPLE_TEXTS: SampleText[] = [
    { text: "This is the best purchase I've ever made! Absolutely love it.", groundTruth: SentimentLabel.Positive },
    { text: "The product arrived broken and the customer service was terrible.", groundTruth: SentimentLabel.Negative },
    { text: "It's an okay product, does the job but nothing special.", groundTruth: SentimentLabel.Neutral },
    { text: "I am overjoyed with the quality and performance. Exceeded my expectations!", groundTruth: SentimentLabel.Positive },
    { text: "Complete waste of money. I regret buying this.", groundTruth: SentimentLabel.Negative },
    { text: "The manual is a bit confusing, but I figured it out eventually.", groundTruth: SentimentLabel.Neutral },
    { text: "Wow, what a fantastic experience from start to finish.", groundTruth: SentimentLabel.Positive },
    { text: "I've had this for a week and it's already falling apart.", groundTruth: SentimentLabel.Negative },
    { text: "The delivery was on time.", groundTruth: SentimentLabel.Neutral },
    { text: "A revolutionary product that changed my daily routine for the better.", groundTruth: SentimentLabel.Positive },
    { text: "I'm so disappointed. It doesn't work as advertised.", groundTruth: SentimentLabel.Negative },
    { text: "The color is slightly different from the picture, but it's fine.", groundTruth: SentimentLabel.Neutral },
    { text: "Highly recommended! You won't be disappointed.", groundTruth: SentimentLabel.Positive },
    { text: "This was a huge letdown. I expected much more.", groundTruth: SentimentLabel.Negative },
    { text: "The packaging was adequate.", groundTruth: SentimentLabel.Neutral },
    { text: "Five stars! An amazing gadget that everyone should own.", groundTruth: SentimentLabel.Positive },
    { text: "The app constantly crashes, making the device unusable.", groundTruth: SentimentLabel.Negative },
    { text: "It functions as expected.", groundTruth: SentimentLabel.Neutral },
    { text: "Incredible value for the price. I'm very impressed.", groundTruth: SentimentLabel.Positive },
    { text: "This is the worst thing I have ever bought online. Avoid at all costs.", groundTruth: SentimentLabel.Negative },
    { text: "The item was delivered to the correct address.", groundTruth: SentimentLabel.Neutral },
    { text: "My life is so much easier now. Thank you for this creation!", groundTruth: SentimentLabel.Positive },
    { text: "I had a very frustrating experience with this company.", groundTruth: SentimentLabel.Negative },
    { text: "The movie was neither good nor bad.", groundTruth: SentimentLabel.Neutral },
    { text: "I'm telling all my friends about this. It's that good!", groundTruth: SentimentLabel.Positive },
    { text: "The quality is cheap and it feels flimsy.", groundTruth: SentimentLabel.Negative },
    { text: "The event proceeded without any major incidents.", groundTruth: SentimentLabel.Neutral },
    { text: "Absolutely phenomenal service and product.", groundTruth: SentimentLabel.Positive },
    { text: "I would not recommend this to anyone. A complete failure.", groundTruth: SentimentLabel.Negative },
    { text: "The meeting was scheduled for 3 PM.", groundTruth: SentimentLabel.Neutral },
    { text: "I am ecstatic about the results. Truly remarkable.", groundTruth: SentimentLabel.Positive },
    { text: "The software is buggy and unintuitive.", groundTruth: SentimentLabel.Negative },
    { text: "This report contains the data you requested.", groundTruth: SentimentLabel.Neutral },
    { text: "An outstanding achievement in technology. Bravo!", groundTruth: SentimentLabel.Positive },
    { text: "I am thoroughly dissatisfied with my experience.", groundTruth: SentimentLabel.Negative },
    { text: "The sky is blue today.", groundTruth: SentimentLabel.Neutral },
    { text: "Could not be happier with this. A true game-changer.", groundTruth: SentimentLabel.Positive },
    { text: "The support team was unresponsive and unhelpful.", groundTruth: SentimentLabel.Negative },
    { text: "The chair has four legs.", groundTruth: SentimentLabel.Neutral },
    { text: "A truly delightful and refreshing movie. I loved every minute.", groundTruth: SentimentLabel.Positive },
    { text: "The food was bland and overpriced. A dreadful dinner.", groundTruth: SentimentLabel.Negative },
    { text: "The cat is sleeping on the mat.", groundTruth: SentimentLabel.Neutral },
    { text: "I was skeptical at first, but this product is genuinely amazing.", groundTruth: SentimentLabel.Positive },
    { text: "This update ruined the app. It's slower and harder to use.", groundTruth: SentimentLabel.Negative },
    { text: "The system is currently online.", groundTruth: SentimentLabel.Neutral },
    { text: "The concert was an unforgettable night of pure joy.", groundTruth: SentimentLabel.Positive },
    { text: "My order was canceled without any explanation. Awful service.", groundTruth: SentimentLabel.Negative },
    { text: "The specifications are listed on the website.", groundTruth: SentimentLabel.Neutral },
    { text: "This book is a masterpiece. I couldn't put it down.", groundTruth: SentimentLabel.Positive },
    { text: "The hotel room was dirty and noisy. A terrible stay.", groundTruth: SentimentLabel.Negative },
];
